apiVersion: v1
kind: Namespace
metadata:
  name: paper-lab
  labels:
    app.kubernetes.io/name: paper-lab
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
