---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: piepy-secret
  namespace: piepy
spec:
  encryptedData:
    BOT_TOKEN: AgCOXI5hLNK8uRpEYoSxt9NweWTvwxcJ5hc1WbW0U7sBDT+0rjnIvjIas/bkqZHtJbSiPHK/ADROBmql0HrR2xNSVWtRVt9NYtYhOGq/HjP8jJ55rjy289HS7m1k4VURJvh1505xFlb2kQLSsLw3YNpiGNsRuspTAVMdncC84llfVun8EqlHVNZ9OwXAXec8eKUiPOUCN3udxP+hN6a5ekt+ItKUXuwWYbIfZX6n+/AYMgOmpR0sDR2EDMppcMvf6EO7AQJiczKmYjSrzrOeYlilh6/nFT2DpJeaviOD1vLpNIctzr2G/JhLd6qDRTG+u6ZnzO2UdOv09fyyZPEHQTSPHBa9G+I4O/LNSX4M0D0SIcZB97fDvlEajMNYY44o7SLdU9Gb1EonL1y1ToatQqdtziFtrS8Ub6f4oUgLnxuQI8JR1VTNyMOBkuScO1amiZDySa7TMH4/117rhRbXPR6psdDYLNhqz9dpWtE5qDRZSn+CLTrQiH5VpbV+ihLn7DqLY766e3uqDeAm3Mt5WJb9IanYLcac6w+2DQ0DghYWIMm5T2fM0/MwG7q5EPre2M1wFKMlCxbChu5nDapNuWPxCp3PUP3chOLenwhQDmmhmHnpf2KWJK+rXkJiGyXYfzYSk8Q615h287q8yMSu1+gywCKfG8tkruYfNHoEYbvUHsGSTTe490uA5NsLJjo6U336oghtalk2E3QhLNbdz6UwMGUxgLP6p1hdXog5OW7cm/OFCwsDDPbDuzMi9F4o8rWb85+IAPbwHeRT2GrP28dr4Yk2U//PnMw=
  template:
    metadata:
      name: piepy-secret
      namespace: piepy
