---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diver-lab-secrets
  namespace: diver-mcs
spec:
  encryptedData:
    RCON_PASSWORD: AgCFwC0t+n8d5C/xVHMgEnRITehU0oA2xJJP/I25idvNnn5HD//7pOWhVXLQ8TA5Cz+DPHY0mEvtJw/gX3DjLQmwe/mB0UA5UIasuty+cHCJUYngN+sp/8w6XdMwKf0lv3RxvBTj2kxroKuxPuUpeU7TbILDx0LGIVzAJAeE39yIZ1ErvZiG+GbKOUGC00d1YjTY951uCMcBzHxc+rvt1tyAkVf0rQLZS1dJaCaOJFiS6lhBg8vzeMBuEqJevgk6cqfKkIn1rwMGkR2rMOyr2130ABXQFZhahkgPh27jZeukMYCKOAbO0V/wY6g2EuOXBWIZgtEt33AISyeXhRQhgMknsRo6efe16eZk6Y34co1nhicv5QgHBThcwjQdGrSwOxrKYl3Ek3DuerXiQVkioSd4EDV1iCqU+FpeDJXgL1jfNhX+cR4L3ASl/1TbCLwF9I0u/8NULUkcCqKxQHusHlAUrS60GRumU1D+GiioB/jxRehWm5uBGBFgbztTt8OcGrg6DEMKFLdWA2MAWm/kpkiVkNWHjmsbmdw0GcUSNMHjH70sDJevhZlKIeKfRH1QsVLD8KjGJRz7Z4YWzn5e5czYQXLzbYmZNzTCMMdNkpPO07szXWAlF7KhA/i8A7id8I8kiSl/BuylfCm5N/L+IPKxQ9oP1qq9TmZkMlf56RA6H2DK3oEaf9eDt7y8oOs6Ht6uSzHIqQMrSuhqa8q13PtS9UsqRR8O++Y=
    VELOCITY_SECRET: AgB4pbj2WWk/KlM6hQeJyo0vOJ/l6yHALFDtaWeLBBkwjE4JUKOvNx2K4/lI0VKlUjOHjUOSNfvoqpSp48R6ckxDh1IGoteLsH1PjXVsH898MimujDdFX60wuo7sPU9o54IqtSmMKukj54n/BCM1WdV1WJVR/oc5qtFfVfeeQxKnt2GIwDP9IMUIGuKpu1ggHQGdrs63dNziYH3dNLF5xq3uHx2wDYYp4IrLXRnu0ramMI67X5GDc3ojVdnBRQW0KC8pBDwXYVadfBjiEbcZbkSyNyseghplSNsQF9/cDDzPQuEHfkwQsSGxII+S6LDOsRXnBhKrbaB+uy0SJU3q8MCg/EtG5/ta/g0CopCmYgpjJTuq/jRnHddGyX3gCWh3Ur+qDkfhmg9LuHNYsQ8OrYO8lZD3nQgRiUjt/gAxVso+NLMZrLEwgGlk3p8RT13XANovNyhqtRARFcyGZLKRtP8/TYvCth/JW1NIzZLmKfz6xxIO2NFqH8+4JGV4xeBHGOK9dd/EIiUJXOSe+xzN5EdSjIf8BtxFd1/mrp8TkVWxyIgPz1mlPttnWBJ4ZLL6RR6OmU7Cf0vCovBhxOmaEmO9rRRh/lR0sp8IiV6KE5iqVUow8t9RWJvqMYLxH8ZripUk2fIASGp5S//zsBEZzcL7fZGca6PJBHd0N2b9DDmAQbtmqCjg0snRW9c/TLy1HVvwVzUxh/CN1p75GOnTf4Gjexb5K3ky2+jAu227YR8A4Q==
  template:
    metadata:
      name: diver-lab-secrets
      namespace: diver-mcs
