apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: central-gateway
  namespace: infra
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.0.0.199

  listeners:
    - name: minegate-je
      port: 25565
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: All
    - name: minegate-be
      port: 19132
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: All

    - name: wireguard
      port: 51820
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: All

    - name: lwyd-front
      port: 3000
      protocol: TCP
      allowedRoutes:
        namespaces:
          from: All
