fullnameOverride: sealed-secrets-controller

rbac:
  create: true

serviceAccount:
  create: true
  name: sealed-secrets-manager

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 256Mi

podLabels:
  app.kubernetes.io/part-of: sealed-secrets

service:
  type: ClusterIP

networkPolicy:
  enabled: false
