apiVersion: v2
name: cilium-gateway
description: The infrastructure cilium gateway
type: application
version: 1.0.0
appVersion: "1.19.4"

dependencies:
  - name: cilium
    version: 1.19.4
    repository: https://helm.cilium.io/
