apiVersion: v1
kind: ConfigMap
metadata:
  name: raw5-config
  namespace: diver-mcs
data:
  paper-global.yml: |
    proxies:
      velocity:
        enabled: false
        online-mode: true
        secret: ${CFG_VELOCITY_SECRET}
    chunk-saver:
      auto-save-interval: 1200
