apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: diver-mcs
resources:
  - ./sealed-secret.yaml
  - ./configmap.yaml
  - ./statefulset.yaml
  - ./gateway.yaml
  - ./temp-gateway.yaml
