---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: raw5-secrets
  namespace: diver-mcs
spec:
  encryptedData:
    RCON_PASSWORD: AgAO2XnJ9GgQ8HoVFHJ2x5da8ZNfZJXA9pja0RsKozc+dBNO2GWKyK1100u4oqoN64/bRLnbNRTHPReMwMMx7WUD26ICVMPGRxsaOTdsM24Am1OumMxBm4J5pilOfwHQCqCLVuTNtmT8Rr7v9aiaEvzktFzuHpXWZ0ei7xVsr/1OTRGdEpeABg7b28sOkUA94qXxyAao0aju/+fzO+ZkpJPk58AJGOIKzt2oEcs08yaxnjDcN4MUdNVCZGAf70Agu57JWqR0eugS0rNYnXVg3R8xeEQjurblaN7jCUtqyuIqvO7F5TjfImtQHivu6qILz17LxouWMOcdk52dLVdSeneUH5ZETDgLau0Gd8kA/CoHLEWD06QO591uw419lFhuCWf/lnGeQ1RASBTfbUMg2lt1ddmfFbIR5IALTg0toIsfGqsE3kOjFjuGt3ulll9vxYLUQmY2iROWqF8Aclbf8Tb3EBlnQZuhDgDyPYx19ZjOkLp+GbWlPNpYR8A9MC4DqgPGkPR9wp83KYynb/E1vUl+yFLMXX8/zioz97vClceBJf4caKrEV/fE9LT2jLVtAxQ3Zzf6HayFeSOpvyftEAHaiOgjG9/34RPdsj/kEsTcKUyrblov07sQxcv75Fv7Gw9o7QJ8RWUJ+v+8A5Qm/+3TBVBqkQxnaTWilCIPdPq8J4SzHeC4YHgGIyZZmjOQg18Wju+LeuZ4J5+6SEH8q9N/bS9ZY/8gdTY=
    VELOCITY_SECRET: AgAdyE5U/WQ79KfxSwieFA15SGQbWKVbKL555No39IZxnLIBFPgYCpBCF0KfD+b4D5XuX6+zeG6sWirtDNU2bbdiZbzCaQVUCMjg+c98Fa/+cv474cYdX4dXZ3STQVnCkv+kTI/kGIyqlmN/7wtKwTZwINOiymPtAoAFe1nHgFxiqTC/e48Jen6dyHvlbeObRg4OCXwkVOSL2swA42qcXZocbeOU9bOc/lMSoamul+RZJ41qIIF4Ljs0+qyAbDuIUUBKM8iJD05zu1rSVyawLODXGTVEw5AIcb/ZgOcKatRFOyeY6X72pneooYj+3IEwgdugggOboMXu5JHprftpZrs8gfBvINxq4f7qzQ6UGS5NeIYyD8ZZqZs0GT+yGAemKpBU7tObmmYzZf2JXr+bCu30udzk8FXA7Zij4TFVyyQTkLjpivZCr+ru6BN2Uv5A0WeVaCu4depfnQ6Q8XFgnw/us5EQns+kgtKCDF3cYHu8rJpPf3c51k9RJngMH/W0X/rX2kv1xaYoTUQj6IUAM/LTYH2yLbfVkS4L+l5xMHXniHigkCCzgfVn6qai9D1XMs1kr82K5G9zI9+Aej8Xw1icaM5fPBAPiu6LhYCTdUhwbNS5m36JnyBZ3/bd2S2dinJqYurtbAQSshyTne2SNJoHaeXmlqg4d7WG684PlsKY3UW39gpRAPiKWk6QKxzG93PUXpfBYhlOnDtr1cDIsly45LVDiEhQZa2LUFZsXUM5SA==
    template:
    metadata:
      name: raw5-secrets
      namespace: diver-mcs
