apiVersion: v1
kind: Service
metadata:
  name: raw5-direct
  namespace: diver-mcs
  annotations:
    io.cilium/lb-ipam-ips: 10.0.0.199
    lbipam.cilium.io/sharing-key: public-vip
    lbipam.cilium.io/sharing-cross-namespace: "*"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: raw5
  ports:
    - name: minecraft-direct
      port: 25566
      targetPort: 25565
