apiVersion: v1
kind: Service
metadata:
  name: lwyd-back
  namespace: lwyd
  labels:
    app.kubernetes.io/name: lwyd-back
spec:
  type: ClusterIP
  selector:
    app: lwyd-back
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
