---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diver-lab-secrets
  namespace: diver-mcs
spec:
  encryptedData:
    RCON_PASSWORD: AgCjCUGEztqhFLuXJ/u7po7osGhfoU/xmD8RBS0mVs7BtPLHjxQf0ua6+q6yL26GSna7bP4xsQvcsCcpab4hxUFCSSDV2crWxn4KLVg1WCBNfyiQS3+a8vMh01paafqauFYHoFiO1JN255QdWga5LgYyOmjtfPhBVMpD+h8Lun87U4SjtRgnJjKnZKLzuY8WcGGRqaRCrHOU2Cq7B5p24jOo/6SQA9FlKRm97o3pAFGMaR1MLPSeRTcNn1LoAXYqAHfsevjKwmwRU5j8Dep7Ty7JU/1vQ/d7Mzh9VfRE3SILDEH7o0j2w600G19zAF6sCWldsZiOqn6c4waOW3nIi3tlzBS0RIrAmHCBvwafWh5jiK0wG/lmQ3wC1Q4Y1c7hjdXEZQAw6RbEUUV/b1/SQfOBGR/YO2790kqJNBlBwPt2+j/RnRjeKDSuEii8RB5KZLXjRhOfzTsNuHBd+UVhfKQ7qqpgTufgaFd84qEFYyu2vumD+tPcf8ckr42sLrrCVwZCZXJGnSCK/7YYFPrqAnix9DWo+YTmwN0HjNJbhfOQznK+hf8DCuGtaywoLkJSr+CSdGSnHbNjD5itbY7v3CrxijRkao52eWZloUaVvlKyFulvhtlQu0Hkxf2A9xDsgWuCqDLBFON9ienv2PeXPGCNnhXojXFies1pGxjFdGx6ctaPq22JElMJfv3s8y/ObCkBd4AZ3ZGvn8pZtF9uWqrERiqvPgYRHQk=
    VELOCITY_SECRET: AgDX4d5VrCfVePZTSTKYZijakj7wQ2CGtbUYmdDkXIbNAN0O8xuJ53nJH1Kje73nqzJGeHh8fcwr1vIXIq6EaYPqLpPWSQGNY04O+RhTgfG3bfY+r857rXgs8hBhLEJrFJHCpKP/dMQhT0gTLrsvonRJ0ksxs/K8MPL/VSx8ZQPTrXX1dItj46NTAfCMu7FwNUqoVGJtM75gGvbvrb60XzDnoq8S53+SQcQBc3AvadTA/L6Ao82ceOQWSJ/P70td7bAD0tunnX8Q5AKZDQoJxNBhgJa33/nBwzdNVoI7RDg1O8o3z7+Y2c8NzXw9r/ZgeZAb+D97L8B2sbejwGLmciqINtDsoKfTEnvnTcbd5+o0SqpFVvJybYV9oYtX0gIPRgTUTgsGeQlkOVsXFhoyO6EgXTowgGng/FQjUQMmpe5V0GaQxOmPksMKlaCVsK9D/vqlj9lW7A6eXaLliTQYRfmygGeGKE0s7x2B3S+CZjFyI4Xtj5yAs6joaldMlTK9CKCyYFt9SBQHyU2+vGYG+9Yxk/AOv+TgTXP7OpjxkH6hvOkPXo1cU2ydFyiXb1nyk9+eY3M4c6lpVygexCy01DknvlPvEPvYPAC9QRZIbescEAXZgd0iHTvQZKnYCj+a7maO/oLcWAP2BSpCgJyH6nqdJ/NU8IHD5VBVcLTYbSe0LBhFVfEMgx5tNeOu7dE1glltMcKicLjj5kZVluqM+HaJTvhlXvpIhtoLnkfHU1SCLA==
  template:
    metadata:
      name: diver-lab-secrets
      namespace: diver-mcs
