apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./sealed-secret-key.yaml
  - ./deployment.yaml
  - ./gateway.yaml

configMapGenerator:
  - name: wireguard-config
    namespace: wireguard
    files:
      - wg0.conf.tpl=./wg0.conf.tpl
