apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-secret
  namespace: wireguard
spec:
  encryptedData:
    privatekey: AgCC5232qkdlUf5zUc4icJSXXbkaZXIZv6OlE/xBObZ0eHqaeSgZCYYiYP4lGfJwuM66JuIwmymlTiXRYIKjXjxg1b1/CQxZ/PxVp66jF6SxAkxKNeh7LLAYWYDpFnD1am//1ZdIdbxi94a20Cy/wCmfl945pwD2KpzmWP1hzhetyOXhlT8LzI5Ahd1u1GmVaB243p4h2H1Xmysnda9AeWNxSeijykMbFSMc/tgcLeW8uE4vT8Xbc08oY7fGu4InH5NVzuuGoA1EzO1nILQfrryBei2qVenYS4D6uDMEnoYEeSkg66PwUqmuNgQEvAvCf+8u/b2/ULLDdKVSuMtvy8NuZlyIqzalwYAIp6cKaF3IpW3YZ3ZpIpE/GpHpLKKPpLEndGngakyMRD1ZdPe4PDiYOtwEurCtL2xCk2NWVgZX/5jJWi0Xd7E3UciwcSWMRFPKecJfHNO3DZNwwK+HBdyfqvhp4f5XG0i0mnocYyhODADk6cVa+TMI4u12JZeEi/OSOi+quqQJwUw3Ry3aTZlZdlWm4i8TCSwlxmHgsNLcQ1XeSBEp8kFF22MUnxg+qci3ljjIwvjetGebDxdG2mkMU2bN+wFmNVdsp667Q3nfRfTv8fHBhb6paOvs2EQAHcYpnFen2Q4zenpVcwlmVXWb6AlmNivKXiBXWTxeF6XPUQsCc1DVdRHYoagU0Q+k6dG2+pkzG/Pc0/9QFFc21QnB3/39bYnMj9ge0CkibG77QY/X2Jfl6O0r6mst1g==
  template:
    metadata:
      name: wireguard-secret
      namespace: wireguard
