---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-server-key
  namespace: wireguard
spec:
  encryptedData:
    privatekey: AgAyoVK30DG3PjdDKLr5axGAt89e/6nZDyx1ZrpMneu7lgk3Jo3W1/x2MQqY/aNU3GE2cBf5dUGUQWT18Fx/mUbqFt5O0tu+iTmfnfu0mywRe8eB1RcPd4UA7/+aOahx7OPtFZFcZC3Gn4Dh8lsUqzBP0ns2exlNckZCcRAvrzEsyhSlrt4oRVe6SzqyCMFPeKN0Jb4qHz1PMmL2nI+aDQSfpAst/gYO70ipfRVVO28DZrMdBwVibVr1AZpix4swpm0hOun+qqSq8Lz6JeLi3AsjXuLC/dwM/YoSOAi0MHuGFGEUR5Obu7axDc17NqSyxEbutomQwP33cWirZBX86+Y6fOBEuOCST2YjnnxP3i0twY4D827NqavBgqQVsvOAZoTYaj8gfZrurtgFtZCdeLqCTBc3aDu+3upYOz5ygRZwJqMsdqceK9q2VdR6Va5BhSa0pGkNp1rOBzndv1eOWi47nW2M9GSYnipwSm80MtQbffsdk0gkbPUjz28vOOjH0nOZ0P2e8yywSpcLBEwf9HRxuxNX8eZIX6Hm0h+exIYfBH52SdWoyB+qo94Vbz0ae8chp/q1dnxIMTz8Si/4UOSMWTAh8FVXd1WMeZDxAIvzXBsBn/jIIdXrlStoty3AngIPXe52SpkNgMGBeJT7EIJbLu7+LvAu75KpGiwCr3TWZpY/dWf4mrkrrjpGfWSOWnHnDI+K6WR5vjVVOOo6okMYd8HI7v0ZyvBsSAOWsVoucy5B6FdxotdlfSaqLQ==
  template:
    metadata:
      name: wireguard-server-key
      namespace: wireguard
