apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    app.kubernetes.io/name: wireguard
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: wireguard
