apiVersion: v1
kind: ConfigMap
metadata:
  name: minegate-config
  namespace: minegate
  labels:
    app.kubernetes.io/name: minegate
data:
  config.yml: |
    config:
      bind: 0.0.0.0:25565
      onlineMode: true

      # example server
      # servers:
      #   lobby: lobby.mc.svc.cluster.local:25565
      # try:
      #   - lobby

      status:
        motd: |
          §bdiver
          §7DIVER!!!!!!!!!!!!!!!!!!!

      # uuid 플레이어 접속 보안 어쩌구용 세팅
      forwarding:
        mode: velocity
        velocitySecret: "${VELOCITY_SECRET}" # ./sealed-secret.yaml 에 박혀있음

      api:
        enabled: false
        bind: 0.0.0.0:8080
