apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minegate

resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./route.yaml

configMapGenerator:
  - name: minegate-config
    files:
      - ./config.yaml
