---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minegate-velocity-secret
  namespace: minegate
spec:
  encryptedData:
    VELOCITY_SECRET: AgCBdBBT9nhGEbErHFKuf0SiX6tVUcfOSyOQvx3z9NSy6g7sMuaVKGRvOvQS7HNFfew/uqIBwnBOXXJZ5p7IWm2Ki48Xo2zB8MhPxxzA4q6d7GNKseAURxSBQH/grxk0fHoJmg9xbFnHi/OW6vQQviirYn3baCdUimea/KktkzRCv+xKfWCiYLAH191gB1d4/JMUnYkWO+dOI/Ouq4qThohC/gmgfW/dLmID8ELlcp9+/HZfBeVuUmovgz1g9+UspMQU84M8H+74SQawaVGaJlxqMV8ojj0Cyho2+HaBXvO7hZNaUv7o4jZRhwXa9BGuUTJCWyZBag3qcZ34DVWtc5iaLB3oODxLHnLG4CbFM0UmU3pBm5SeP+RYv6Ewx4xopLZ0b87qxaufT41chDvLXV3IhHY3AHVmwzMhQHA/Sc7hh917TrZyFOxQ1Z8FWl41GH2jHuAVp6iw0QxqgyU5V1Z6DnFlZHW+nD8mwLAWnemgHBFEy3TVOAoCC3Z2EVS+JEHOvdA9V26xUE/gcpNalP58b/DEgOVMjjNFMJ+qZE78Iwh96sg1JdKwqwTU8zSEor7Rl2n/FND/NtZrTuka5/uaiM0bK32BwRV+2ZsvQmMIjHxoBMSIXWt4VUYEpN7HAnV5TGmQTIFWjzie7dxAKv2EC4AylHZyeckykZJ+KoOUZAooN0VvIpwknMwCN1DgY6twet6fw+t2W6sGdvDhP8z6hvq6akHp5+GJ/6l1Pkt4vQ==
  template:
    metadata:
      name: minegate-velocity-secret
      namespace: minegate
