apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minegate-secret
  namespace: minegate
spec:
  encryptedData:
    velocitySecret: AgCH8InYNgd9gGY/WiN9vLnDta3KtcxXxlQmzHy7AjiiF6gN3cvRiasmtPhtEUJhQYvO+Rn8MJbMy4qDlL/ZAsSJYsUkHDNdxOx8kAtdw7h1CG0GJF8rFTDYhhs+iHVCB435KcXlTUWWIgVLjKvLdLbvWATZsTMktsJpf+SMSzQyJd+wr9G5Mh0zDXMkFOjxJThMby0Visd+UGKdPWEcStrYCupxvCAaS1+8TkZJE1mrPlY3YlWLTYPHj1YVkL3znLtce9TRX3ppOEdr5YLu8WnCGC60Ra7Yr5rNyBhz289cnwQ5aZWA18q9gqDuf53KxdAYMeMFICHjqtcQgyIKnEh79nWGNA7fqSNG4FomQjKXna7UGjuYwPOy51AfDN+/9mBj5W2nC0PjRScI+nBjnGbu3WYYcNwI00bPq+AXWYH91aodCifHbrkGlPXBx0CrWpFzdx2Z9o8K9BVr3uZZUlqlP5Ia5DjgbPL7aTaQqv+6iMrj4Xj9/jbvvMXKoKmt4Kipw0HSkbqx6CG2g6snmGC/aNKw1p/B+d/0Dvo/yCVn3P15ltcEuoh2VJTDestkRNyjoJRo3vF5VAdQmVdjlbthJJM55pjhrYn5QV0tQDSffDdbo8KXIaB6Q4KjbOZ0dSI1dLnv9Lu2JLzXdbCnPYblLtwkFTHtN2kRpUy6uKhu8Q/vVdtpy8tq8z0wNIIMA0Txl7wcA2PiLCjGOX71045q4YRtyQjPDOIVhkQWHYx5Fw==
  template:
    metadata:
      name: minegate-secret
      namespace: minegate
